USE movie_chat_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS chat_rooms;
DROP TABLE IF EXISTS chat_messages;
DROP TABLE IF EXISTS bookmarks;

SET FOREIGN_KEY_CHECKS = 1;
